services:
  - type: web
    name: retell-custom-llm
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RETELL_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ORGANIZATION_ID
        sync: false
      - key: ACCOUNT_STATUS_API_ENDPOINT
        sync: false
      - key: ACCOUNT_STATUS_API_KEY
        sync: false
      - key: DEV
        value: false
